import logging
import json
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from llm.factory import get_llm_with_failover

LOGGER = logging.getLogger(__name__)

class ValidationAgent:
    def __init__(self):
        self.llm = get_llm_with_failover()
        self.parser = JsonOutputParser()
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are a strict Validation and Safety Agent.
Review the output generated by a specialized agent. Ensure the answer is safe, professional, and properly grounded.
If the answer makes unverified hallucinated claims about the provided source data, correct it or state it is unverified.
You MUST output raw JSON with this exact structure:
{{
  "answer": "The finalized safe answer or the corrected version.",
  "source": "The source inherited from context (e.g. 'company.db', 'Tool Execution', explicit document names).",
  "confidence": "high | medium | low"
}}"""),
            ("human", "User Query: {query}\n\nAgent Output: {answer}\n\nAgent Source Context: {source}\n\nPlease validate and return the required JSON.")
        ])
        
        self.chain = prompt | self.llm | self.parser

    def validate(self, query: str, agent_result: dict) -> dict:
        LOGGER.info("Validating agent result.")
        try:
            val = self.chain.invoke({
                "query": query,
                "answer": agent_result.get("answer", str(agent_result)),
                "source": agent_result.get("source", "generic")
            })
            
            # Ensure proper shape format fallback
            if "answer" not in val:
                val["answer"] = agent_result.get("answer", "")
            if "source" not in val:
                val["source"] = agent_result.get("source", "generic")
            if "confidence" not in val:
                val["confidence"] = "medium"
                
            return val
        except Exception as e:
            LOGGER.exception("Validation Agent JSON parse failed.")
            return {
                "answer": agent_result.get("answer", str(agent_result)),
                "source": agent_result.get("source", "validation_fallback"),
                "confidence": "low"
            }
